# Generated by Django 4.1.7 on 2023-05-16 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxymodelapp', '0002_delete_student_delete_teacher_doctor_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=12)),
                ('pesel', models.CharField(blank=True, max_length=12)),
                ('sex', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+48 999-999-999'.", regex='\\b\\d{2}\\s\\d{3}-\\d{3}-\\d{3}\\b')])),
                ('height', models.CharField(blank=True, max_length=5)),
                ('postal_code', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message="Postal code must be entered in the format: '42-600'.", regex='\\b\\d{2}-\\d{3}\\b')])),
                ('city', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Incorrect city format.', regex='^[A-ZĄĆĘŁŃÓŚŹŻa-ząćęłńóśźż ]+(?:[\\s-][A-ZĄĆĘŁŃÓŚŹŻa-ząćęłńóśźż ]+)*$')])),
                ('street', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Incorrect street format.', regex='^[A-ZĄĆĘŁŃÓŚŹŻa-ząćęłńóśźż ]+\\s\\d+[A-Z]?\\/?\\d*\\b')])),
                ('name_to_contact', models.CharField(blank=True, max_length=30)),
                ('surname_to_contact', models.CharField(blank=True, max_length=30)),
                ('phone_number_to_contact', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+48 999-999-999'.", regex='\\b\\d{2}\\s\\d{3}-\\d{3}-\\d{3}\\b')])),
                ('connection_with_patient', models.CharField(blank=True, max_length=30)),
                ('illness', models.CharField(blank=True, max_length=200)),
                ('allergies', models.CharField(blank=True, max_length=200)),
                ('addiction', models.CharField(blank=True, max_length=200)),
                ('had_covid19', models.CharField(blank=True, max_length=5)),
                ('date_of_covid19', models.CharField(blank=True, max_length=15)),
                ('covid19_vaccinated', models.CharField(blank=True, max_length=5)),
                ('date_of_covid19_vaccinated', models.CharField(blank=True, max_length=15)),
                ('name_of_drug', models.CharField(blank=True, max_length=30)),
                ('drug_dose', models.CharField(blank=True, max_length=10)),
                ('m_a_e_drug_dose', models.CharField(blank=True, max_length=15)),
                ('extra_informations', models.CharField(blank=True, max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxymodelapp.patient')),
            ],
        ),
    ]
